### ISSUE TITLE
Предупреждение перед закрытием окна ввода данных по абитур. / магистр. 

### ISSUE THREAD

**Issue by ahterov** [gjrfytn/pk#90]
При нажатии на "X" выводить предупреждение о том, что не сохраненные данные (если такие есть) будут удалены

**Comment by gjrfytn** [comment]
Но пока лучше выводить его всегда, т.к. долго делать проверку на внесённые изменения.

**Comment by ahterov** [comment]
Тогда лучше написать: Вы уверены, что хотите закрыть форму?
